### ISSUE TITLE
I need a tutorial

### ISSUE THREAD

**Issue by txj-mssl** [Castlemark/JRPG-Builder#1]
thanks

**Comment by Castlemark** [comment]
Hey, thanks for taking an interest in JRPG Builder! I just created a documentation file you can find [here](https://github.com/Castlemark/JRPG-Builder/blob/master/DOCUMENTATION.md). It explains the basics of creating content and gives some examples, you'll also find and example campaign in this repo. 

I've also made a release that you can find [here](https://github.com/Castlemark/JRPG-Builder/releases/tag/0.5.0) to directly download the binaries and an example campaign (this campaign isn't pretty, but should help you understand the basics). 

If you have any more problems or suggestions don't hesitate to open another issue or send me a message,

P.S. For some reason github didn't notify me an issue was opened in the repo
